name: ci
on:
  deployment_status:
    environment: protected
    state: success
jobs:
  print:
    runs-on: self-hosted
    steps:
      - name: Debug github event
        run: echo '${{ github.event }}'
      - if: github.event.deployment_status.state == 'success'
        run: echo 'DEPLOY SUCCESS!'
      
