on:
  push:
    branches:
      - main
jobs:
  tf_apply:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - uses: jwalton/gh-find-current-pr@v1.3.2
        id: find_pr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: all

      - uses: actions/download-artifact@v3
#        if: success() && steps.findPr.outputs.number
        with:
          name: tfplan-${{ github.event.repository.name }}-test-pr-${{ steps.find_pr.outputs.pr }}
          path: ~/download/artifacts
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ~/download/artifacts

      - name: Terraform Init
        id: terraform_init
        run: terraform init

      - name: Terraform Apply
        id: terraform_apply
        run: terraform apply -auto-approve ~/download/artifacts/myplan.tfplanh
